<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="4" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Family_Facts" duration-ms="80007" started-at="2014-09-16T12:41:53Z" finished-at="2014-09-16T12:43:13Z">
    <groups>
    </groups>
    <test name="Family_Facts" duration-ms="80007" started-at="2014-09-16T12:41:53Z" finished-at="2014-09-16T12:43:13Z">
      <class name="testCases.FamilyFactsGuest">
        <test-method status="PASS" signature="scripExecuterIntializer()[pri:0, instance:testCases.FamilyFactsGuest@b1959]" name="scripExecuterIntializer" is-config="true" duration-ms="2" started-at="2014-09-16T18:11:53Z" finished-at="2014-09-16T18:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scripExecuterIntializer -->
        <test-method status="FAIL" signature="module1tc1()[pri:0, instance:testCases.FamilyFactsGuest@b1959]" name="module1tc1" duration-ms="11511" started-at="2014-09-16T18:11:53Z" finished-at="2014-09-16T18:12:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Discover the meaning and history behind your last name test] but found [Discover the meaning and history behind your last name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Discover the meaning and history behind your last name test] but found [Discover the meaning and history behind your last name]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at keyWords.Keywords.verifyContentMatch(Keywords.java:516)
	at keyWords.KeywordHandler.keywordhandler(KeywordHandler.java:73)
	at keyWords.ScriptExecuter.execute(ScriptExecuter.java:36)
	at testCases.FamilyFactsGuest.module1tc1(FamilyFactsGuest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- module1tc1 -->
        <test-method status="FAIL" signature="module1tc1()[pri:0, instance:testCases.FamilyFactsGuest@b1959]" name="module1tc1" duration-ms="11162" started-at="2014-09-16T18:12:05Z" finished-at="2014-09-16T18:12:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Discover the meaning and history behind your last name test] but found [Discover the meaning and history behind your last name]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Discover the meaning and history behind your last name test] but found [Discover the meaning and history behind your last name]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at keyWords.Keywords.verifyContentMatch(Keywords.java:516)
	at keyWords.KeywordHandler.keywordhandler(KeywordHandler.java:73)
	at keyWords.ScriptExecuter.execute(ScriptExecuter.java:36)
	at testCases.FamilyFactsGuest.module1tc1(FamilyFactsGuest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- module1tc1 -->
        <test-method status="PASS" signature="module1tc2()[pri:0, instance:testCases.FamilyFactsGuest@b1959]" name="module1tc2" duration-ms="20425" started-at="2014-09-16T18:12:16Z" finished-at="2014-09-16T18:12:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- module1tc2 -->
        <test-method status="PASS" signature="clearcookies()[pri:0, instance:testCases.FamilyFactsGuest@b1959]" name="clearcookies" is-config="true" duration-ms="318" started-at="2014-09-16T18:12:37Z" finished-at="2014-09-16T18:12:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearcookies -->
      </class> <!-- testCases.FamilyFactsGuest -->
      <class name="testCases.FamilyFactsRegistered">
        <test-method status="PASS" signature="clearlogs(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testCases.FamilyFactsRegistered@133a7af]" name="clearlogs" is-config="true" duration-ms="8829" started-at="2014-09-16T18:11:45Z" finished-at="2014-09-16T18:11:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[remote]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[saucelabs]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[31]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[OSX 10.8]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[1024x768]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearlogs -->
        <test-method status="PASS" signature="scripExecuterIntializer()[pri:0, instance:testCases.FamilyFactsRegistered@133a7af]" name="scripExecuterIntializer" is-config="true" duration-ms="0" started-at="2014-09-16T18:12:37Z" finished-at="2014-09-16T18:12:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- scripExecuterIntializer -->
        <test-method status="FAIL" signature="module2tc1()[pri:0, instance:testCases.FamilyFactsRegistered@133a7af]" name="module2tc1" duration-ms="36263" started-at="2014-09-16T18:12:37Z" finished-at="2014-09-16T18:13:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [zenfbitesterkp1] but found [ZenFbitesterkp1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [zenfbitesterkp1] but found [ZenFbitesterkp1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at keyWords.Keywords.verifyContentMatch(Keywords.java:511)
	at keyWords.KeywordHandler.keywordhandler(KeywordHandler.java:73)
	at keyWords.ScriptExecuter.execute(ScriptExecuter.java:36)
	at testCases.FamilyFactsRegistered.module2tc1(FamilyFactsRegistered.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- module2tc1 -->
        <test-method status="PASS" signature="clearcookies()[pri:0, instance:testCases.FamilyFactsRegistered@133a7af]" name="clearcookies" is-config="true" duration-ms="311" started-at="2014-09-16T18:13:13Z" finished-at="2014-09-16T18:13:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearcookies -->
        <test-method status="PASS" signature="writeResult()[pri:0, instance:testCases.FamilyFactsRegistered@133a7af]" name="writeResult" is-config="true" duration-ms="648" started-at="2014-09-16T18:13:14Z" finished-at="2014-09-16T18:13:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeResult -->
      </class> <!-- testCases.FamilyFactsRegistered -->
    </test> <!-- Family_Facts -->
  </suite> <!-- Family_Facts -->
</testng-results>
